#server:
#  port: 19999
#
#
#minio:
#  endpoint: http://192.168.0.196
#  uploadPort: 9000
#  downloadPort: 9001
#  accessKey: 51B6P21DHJFLAZPLHGUD
#  secretKey: iaZQUdMsSojTlZZqNNAslXiBzIQr1pr2S9YptR7w
#  # token的有效时长
#  tokenTimeout: 60
#
#spring:
#  servlet:
#    multipart:
#      # 最大单个文件上传大小
#      max-file-size: 10MB
#      enabled: true
#      #单次请求最大文件上传大小
#      max-request-size: 30MB

#  .endpoint("http://192.168.0.196:9000/")
#  .credentials("51B6P21DHJFLAZPLHGUD", "iaZQUdMsSojTlZZqNNAslXiBzIQr1pr2S9YptR7w")
#  .bucket("glmall")
#  :9001
# :9000