#server:
#  port: 9000
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.196:3306/glmall-product?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  application:
#    name: glmall-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.0.196:8848
#        enabled: true
#
#mybatis-plus:
#  # \u4E0D\u914D\u7684\u8BDD\uFF0C\u9ED8\u8BA4\u8DEF\u5F84\uFF1Aclasspath*:/mapper/**/*.xml\uFF0Cclasspath*\u626B\u63CF\u6240\u6709\u4F9D\u8D56\u5305\u4E0B\u7684\u7C7B\u8DEF\u5F84
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      # \u4E3B\u952E\u81EA\u589E
#      id-type: auto
#
## \u66B4\u9732\u7AEF\u70B9
##management:
##  endpoints:
##    web:
##      exposure:
##        include: *
spring:
  redis:
    host: 192.168.0.196
    port: 6379
    password: 123456
  cache:
    type: redis
    redis:
      time-to-live: 360000
glmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10